### ISSUE TITLE
chisel3.internal.ChiselException: operand has escaped the scope of the when in which it was constructed

### ISSUE THREAD

**Issue by IAMAl** [riscv-software-src/riscv-tests#379]
My code have issue of
"""
[info] - should Test: niconicoProc *** FAILED ***
[info]   chisel3.internal.ChiselException: operand has escaped the scope of the when in which it was constructed
[info]   at chisel3.internal.throwException$.apply(Error.scala:85)
[info]   at chisel3.Data.requireVisible(Data.scala:458)
[info]   at chisel3.Data.ref(Data.scala:480)
[info]   at chisel3.Element.ref(Element.scala:50)
[info]   at chisel3.Bits.binop(Bits.scala:201)
[info]   at chisel3.Bool.do_$amp(Bits.scala:1126)
[info]   at chisel3.Bool.do_$amp$amp(Bits.scala:1160)
[info]   at rob.ROB.$anonfun$new$34(rob.scala:150)
[info]   at chisel3.Data.$anonfun$$colon$eq$1(Data.scala:522)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
"""
**Code**:
https://github.com/IAMAl/ChiselLivesMatter/tree/main/niconicoProcessor

**sbt version**: sbt 1.5.5 (AdoptOpenJDK Java 11.0.11)

**tester2 version**: "chiseltest"  -> "0.3.0+"

**Comment by IAMAl** [comment]
Oh, this post should be chisel repo, sorry.
