### ISSUE TITLE
Instructions should mention that `pexpect` is a prerequisite for debug tests?

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [riscv-software-src/riscv-tests#510]
Initial attempt to run the debug tests resulted in this error:
```
echo $PATH
/home/user/Downloads/riscv-gnu-toolchain/installed-tools/bin:/home/user/Downloads/riscv-openocd/installed-tools/bin:...

git clone --recursive https://github.com/riscv-software-src/riscv-tests
...

cd riscv-tests/debug
make
Traceback (most recent call last):
  File "/home/user/Downloads/riscv-tests/debug/./gdbserver.py", line 14, in <module>
    import targets
  File "/home/user/Downloads/riscv-tests/debug/targets.py", line 7, in <module>
    import testlib
  File "/home/user/Downloads/riscv-tests/debug/testlib.py", line 12, in <module>
    import pexpect
ModuleNotFoundError: No module named 'pexpect'
Traceback (most recent call last):
  File "/home/user/Downloads/riscv-tests/debug/./gdbserver.py", line 14, in <module>
    import targets
  File "/home/user/Downloads/riscv-tests/debug/targets.py", line 7, in <module>
    import testlib
  File "/home/user/Downloads/riscv-tests/debug/testlib.py", line 12, in <module>
    import pexpect
ModuleNotFoundError: No module named 'pexpect'
echo Finished spike64
Finished spike64
echo Finished spike64-2
Finished spike64-2
```
Installing `pexpect` fixes the problem but this doesn't seem to be mentioned anywhere as a prerequisite:
```
sudo pip install pexpect
...

make
./gdbserver.py \
        ./targets/RISC-V/spike64.py \
        CeaseStepiTest \
        --isolate \
        --print-failures \

Using $misa from hart definition: 0x8000000000141125
[CeaseStepiTest] Starting > logs/20231003-223042-spike64-CeaseStepiTest.log
[CeaseStepiTest] not_applicable in 0.00s
::::::::::::::::::::::::::::[ ran 1 tests in 0s ]:::::::::::::::::::::::::::::
1 tests returned not_applicable
./gdbserver.py \
        ./targets/RISC-V/spike64.py \
        CheckMisa \
        --isolate \
        --print-failures \

Using $misa from hart definition: 0x8000000000141125
[CheckMisa] Starting > logs/20231003-223042-spike64-CheckMisa.log
[CheckMisa] pass in 1.35s
::::::::::::::::::::::::::::[ ran 1 tests in 1s ]:::::::::::::::::::::::::::::

...
```

**Comment by TommyMurphyTM1234** [comment]
On WSL2/Ubuntu 22.04 I had to manually install `pexpect`.
On VirtualBox VM/Zorin OS Lite 16.3 (Ubuntu 22.04 derivative) I did not.
